import streamlit as st
import openai
import google.generativeai as genai


client = openai.OpenAI(api_key = "")       #Chat GPT
genai.configure(api_key= "")                #Gemini


st.title("AI Generator App")
st.markdown("**Generate text using Gemini or GPT**")

prompt = st.text_area("Enter your prompt..")

#Model selection
model_choice = st.radio("Choose a model" , ("GPT (OpenAI)" , "Gemini (Google)"))

if st.button("Generate...."):
    with st.spinner("Generating...."):
        if model_choice == "GPT (OpenAI)":
            message = [{"role" : "user" , "content" : prompt}]
            response = client.responses.create(
                model = "gpt-4.1-nano",
                input = message
            )
            st.success("Response generated by GPT-")
            st.write(response.output_text)
        else:
            model = genai.GenerativeModel('models/gemini-2.5-flash')
            response = model.generate_content(prompt)
            st.success("Response generated by Gemini-")
            st.write(response.text)