# -*- coding: utf-8 -*-
"""genai_3_gpt_image.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EI09qhniDjWPuKBuah7akUxph42btYwE
"""

import openai

import os
from google.colab import userdata

os.environ["OPEN_API_KEY"] = userdata.get('o_key')

client = openai.OpenAI(
    api_key = os.environ.get("OPEN_API_KEY")
)

#Generate the image
response = client.images.generate(
    model = "dall-e-3",
    prompt = "A lion having coffee in a coffee shop.",
    n = 1,
    size = "1024x1024",
    quality = "standard"
)

image_url = response.data[0].url

from IPython.display import Image,display
display(Image(url = image_url))

#Generate the image
def generate_image(prompt):
  response = client.images.generate(
      model = "dall-e-3",
      prompt = prompt,
      n = 1,
      size = "1024x1024",
      quality = "standard"
  )

import gradio as gr

gr.Interface(fn = generate_image, inputs = "text" , outputs="image" , title="Image Generator").launch()

